# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9dc65aaeec2151124792f25e6da8f3e6bbca6e98df70d36330f372bd7f2f514cf48bea5da36303866b92f71818b88ffda5befe271627e10e8d02a5640d7687c

test:
  secret_key_base: facb81c0442a4850803fe9d0996d66d6ee3877c471069b5790d8c5f5f5c34f1bba7b9fcf91d0d8c77d41e1ca2ef2faa0eafa1f1367828e0cb870e057d5cb30ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
